Added documentation for key binding, contributions and registry
eclipsesource/theia pull request #10
Opened 2020-10-02 13:04 UTC by JonasHelming

Contributed on behalf of STMicroelectronics

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

#### What it does

#### How to test

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2020-10-02 14:10 UTC, tortmayr commented on packages/core/src/common/keybinding.ts
> + * A Keybinding binds a specific key sequence ({@link keybinding}) to trigger a command ({@link command}). A Keybinding optionally may
```suggestion
 * A Keybinding binds a specific key sequence ({@link Keybinding#keybinding}) to trigger a command ({@link Keybinding#command}). A Keybinding optionally may
```

2020-10-02 14:10 UTC, tortmayr commented on packages/core/src/common/keybinding.ts
> + * define a "when clause" ({@link when}) to specific in which context it becomes active.
```suggestion
 * define a "when clause" ({@link Keybinding#when}) to specify in which context it becomes active.
```

2020-10-02 15:52 UTC, koegel requested changes
Minor changes

2020-10-02 15:52 UTC, koegel commented on packages/core/src/common/keybinding.ts
> +     * A clause defining the condition when the Keybinding is active, e.g. based on the current focus.
```suggestion
     * A optional clause defining the condition when the Keybinding is active, e.g. based on the current focus.
```

2020-10-02 15:52 UTC, koegel commented on packages/core/src/common/keybinding.ts
> +     * Arguments that will be passed to the command when it gets triggered via this KeyBinding.
```suggestion
     * Optional arguments that will be passed to the command when it gets triggered via this KeyBinding.
```

2020-10-07 08:01 UTC, tortmayr approved these changes

2022-11-16 14:01 UTC, sdirix commented
Merged upstream with https://github.com/eclipse-theia/theia/pull/8637

2022-11-16 14:01 UTC, closed without merging