[WIP] Provide API to filter unwanted contributions
eclipsesource/theia pull request #17
Opened 2021-03-22 07:40 UTC by tortmayr

Fixes #9069
Signed-off-by: Tobias Ortmayr tortmayr@eclipsesource.com
Contributed on behalf of STMicroelectronics

#### What it does

#### How to test

#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2021-03-26 08:19 UTC, sdirix requested changes
Looks good overall.

Some generic comments:
 - We need to clarify which copyright notice we want to use for new files
 - I think the offered filters are good in general, I wonder if we could go with a more generalized approach. What do you think?

2021-03-26 08:19 UTC, sdirix commented on packages/core/src/common/contribution-filter/filter.ts
> +export type PatternMatchingType = 'equals' | 'includes' | 'regex';
Did you go this way so the filter can be defined declaratively? What do you think of a compositional approach where the filter takes two functions, one to extract the attribute to compare and one to compare the attributes? Then we could offer different utilities for comparing and one could be this pattern-matching string comparison which is able to be defined declaritively.

2021-03-31 09:46 UTC, tortmayr commented on packages/core/src/common/contribution-filter/filter.ts
> +export abstract class StringBasedFilter<T extends Object> implements Filter<T> {
There was a bug in inversify some time ago that made it necessary to also declare abstract classes as `@injectable`. I'm not sure if this still is the case, I will investigate this

2021-04-02 14:46 UTC, tortmayr commented on packages/core/src/common/contribution-filter/filter.ts
> +export abstract class NameBasedFilter<T extends Object> extends StringBasedFilter<T> {
Yes, unfortunately every superclass of an injectable class has to be injectable as well otherwise inversify will fail with a runtime error a la `Missing required @injectable annotation`

2021-04-07 05:41 UTC, tortmayr commented on packages/core/src/common/contribution-filter/contribution-filter.ts
> +    contributions?: ContributionType[];
Done

2021-04-07 05:41 UTC, tortmayr commented on packages/core/src/common/contribution-filter/filter.ts
> +        if (!filterStr) {
Done

2021-04-07 05:42 UTC, tortmayr commented on packages/core/src/common/contribution-filter/filter.ts
> +export interface Identifable {
Done

2021-04-07 05:42 UTC, tortmayr commented on packages/core/src/common/contribution-filter/filter.ts
> +}
Done

2021-04-07 05:42 UTC, tortmayr commented on packages/core/src/common/contribution-filter/filter.ts
> +export abstract class StringBasedFilter<T extends Object> implements Filter<T> {
Yes, see comment above

2021-04-07 05:44 UTC, tortmayr commented on packages/core/src/common/contribution-filter/filter.ts
> +export type PatternMatchingType = 'equals' | 'includes' | 'regex';
No particular reason why I went this way. Just reapplied the same approach that we used in the POC. I did rework this to a compositional approach with utility functions.

2021-04-07 05:53 UTC, tortmayr commented
Thanks for the review.
@sdirix I addressed your comments/issues and also added a test for the contribution filter and prepared a changelog update.
While revisiting the FilterAPI I noticed that the `IdBasedContributionFilter` was actually dead code from the POC that we migrated on accident so I removed it.

2021-04-07 16:19 UTC, sdirix requested changes

2021-04-07 16:19 UTC, sdirix commented on packages/core/src/common/contribution-filter/filter.ts
> + */
```suggestion
/**
 * Applies a set of filters to a set of given objects and returns the set of filtered objects.
 * @param toFilter Set of objects which should be filtered
 * @param filters Set of filters that should be applied
 * @param negate Negation flag. If set to true the result of all `Filter.test` methods is negated
 * @returns The set of filtered arguments
 */
```

2021-04-07 16:19 UTC, sdirix commented on packages/core/src/common/contribution-filter/string-based-filter.ts
> +     * Tests wether the object should be filtered out based on its string representation.
```suggestion
     * Tests whether the object should be filtered out based on its string representation.
```

2021-04-07 16:19 UTC, sdirix commented on packages/core/src/common/contribution-filter/contribution-filter.ts
> +     * will be applied to all contribution types.
We should give an example contribution type as it's hard to know what exactly is expected here.

2021-04-07 16:23 UTC, sdirix commented
@tortmayr I applied the code review myself. It's almost only doc changes, however I changed the functionality in the registry getter. Can you recheck that code?

2021-04-08 08:26 UTC, tortmayr commented
Thanks for the fixes. Looks good to me now. :+1:

2021-04-08 11:38 UTC, sdirix approved these changes

2022-11-16 14:07 UTC, sdirix commented
Merged upstream with https://github.com/eclipse-theia/theia/pull/9317

2022-11-16 14:07 UTC, closed without merging