Performance measurement
eclipsesource/theia pull request #19
Opened 2021-07-19 10:28 UTC by sgraband

#### What it does

This commit adds a script for performance measurement using the Google DevTools tracing.
Currently the startup time of the browser-app is being measured.
The script uses Puppeteer so other processes can be measured in the future as well.
For more information see the `README.md` in the scripts/performance directory.

Contributed on behalf of STMicroelectronics

Signed-off-by: sgraband@eclipsesource.com
#### How to test

See the README on how you can run the script manually or run the `performance:startup` node script in the root directory to measure the startup time. You can also adjust the parameters in the `performance:startup:script` node script to have more runs for example or to run the test headful.
Additionally, you can import the generated `scripts/performance/profiles/startupProfile.json` file in the the performance tab of the Google DevTools.
#### Review checklist

- [ ] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2021-07-23 07:36 UTC, sdirix requested changes
Works for me!

I get this weird warning during execution:
> The node binary used for scripts is /tmp/yarn--1627025300882-0.06251617126804576/node but npm is using /home/stefan/.nvm/versions/node/v12.22.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was
 executed with.

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/README.md
> +This directory contains a script that measures the performance of theia.
```suggestion
This directory contains a script that measures the performance of Theia.
```

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/README.md
> +Currently the support is limited to measuring the `browser-app`s startup time using the `Largest contentful Paint (LCP)` value.
```suggestion
Currently the support is limited to measuring the `browser-app`s startup time using the `Largest contentful paint (LCP)` value.
```

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/README.md
> +To run the script the theia backend needs to be started.
```suggestion
To run the script the Theia backend needs to be started.
```

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/README.md
> +Additionally, the root package.json file contains node scripts that startup the backend as well as the script. Like the `performance:startup` script.
```suggestion
Additionally, the root package.json file contains node scripts that startup the backend as well as the script.
See the `performance:startup` script.
```

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/README.md
> +-   `--url`: Point theia to a url for example for specifying a specifc workspace (default: `http://localhost:3000/#/<absolutePathToWorkspaceFolder>`)
```suggestion
-   `--url`: Point Theia to a url for example for specifying a specifc workspace (default: `http://localhost:3000/#/<absolutePathToWorkspaceFolder>`)
```

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/measure-performance.js
> +async function measureStartup(profilePath, name, runNr, multipleRuns) {
* Does this need to be `async`?
 * I would rename this to something like: analyzeStartup which returns the parsed values. The function calling this one then calls `logDuration` with the result. The idea is to separate between file analysis and IO.

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/profiles/.gitignore
> +# This folder contains all the generated performance profiles.
Do we need this directory? We could also just check whether it exists and create it if necessary in our script.

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/workspace/.gitignore
> +# This just checks in an empty workspace for the performance measurements.
Do we need this directory? We could also just check whether it exists and create it if necessary in our script.

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/measure-performance.js
> +let url = 'http://localhost:3000/#' + path;
I would just handin the whole url via a parameter. then this script can be used with arbitrary Theia instances.

2021-07-23 07:36 UTC, sdirix commented on package.json
> +    "performance:startup": "start-server-and-test start:browser 3000 performance:startup:script",
Do we have to wait for the Theia app to start before executing the performance script? We could also do that check in our script ourselves, right? Then we don't need the dependency and only need to add one script here.

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/measure-performance.js
> +        console.log(performanceTag + braceText(name) + braceText('STDEV') + ' ' + lcp + ': ' + calculateStandardDeviation(mean, durations));
Missing `seconds` at the end

2021-07-23 07:36 UTC, sdirix commented on scripts/performance/measure-performance.js
> +        await page.waitForSelector('.fa-exclamation-triangle', { state: 'visible' });
Please add a comment why this selector was chosen and what it's actually choosing

2021-07-23 07:43 UTC, sdirix commented
Please check whether you can add
```
// @ts-check
```
to the script

2021-07-23 13:03 UTC, sgraband commented on scripts/performance/measure-performance.js
> +let url = 'http://localhost:3000/#' + path;
If you pass a URL as a parameter you need to specify the whole URL. This is just done, to have a relative path to the workspace for the default value.

2021-07-23 13:07 UTC, sdirix commented on scripts/performance/measure-performance.js
> +let url = 'http://localhost:3000/#' + path;
Wouldn't this be more flexible? Now it's only possible to test locally hosted Theia. With the full URL you can even test deployed Theias. Maybe use url if it's given (default to `http://localhost:3000/#`) and append the `path` when given

2021-07-23 13:40 UTC, sgraband commented on scripts/performance/measure-performance.js
> +let url = 'http://localhost:3000/#' + path;
If you pass anything with the `--url` parameter the url will be completly overwritten. Hence, you could just call the script with your hosted url. However with this you cannot just append a workspace to the `http://localhost:3000/#`. Should i split the arguments into domain and workspace?

2021-07-23 13:44 UTC, sgraband commented
I updated my changes with your feedback. Regarding the error you mentioned: This should not happen anymore. (I added a npm preference, that prepends the node path)

Additionally i enabled the ` @ts-check`. There was however a small problem with the puppeteer selectors, so i ignored those lines.

2021-07-23 13:45 UTC, sdirix commented on scripts/performance/measure-performance.js
> +let url = 'http://localhost:3000/#' + path;
Ah I see, I did not recognize that `url` was already a parameter. But if the `url` is given we should probably not call `getOrCreateFolder(path)`, right?

2021-07-23 13:50 UTC, sgraband commented on scripts/performance/measure-performance.js
> +let url = 'http://localhost:3000/#' + path;
Good Catch! I will add a check whether or not a url has been passed.

2021-07-23 14:36 UTC, sdirix commented
The `yarn.lock` changes can be removed

2021-07-23 14:45 UTC, sdirix commented on package.json
> +    "performance:startup": "concurrently --success first -k -r \"yarn performance:script --name Startup --folder startup --runs 2\" \"yarn start:browser\"",
Maybe inline the `performance:script` and remove the separate `performance script`

2021-07-26 08:32 UTC, sgraband commented
Removed the `yarn.lock` changes and updated the `package.json`.

2021-07-26 09:14 UTC, sdirix requested changes
The `profiles` folder and default workspace folder should still be ignored, however by a `.gitignore` in the `scrips/performance` directory.

2021-07-26 09:14 UTC, sdirix commented on scripts/performance/README.md
> +See the `performance:startup` script.
```suggestion
### Quick Start

Execute `yarn run performance:startup` in the root directory.

### Prerequisites

To run the performance tests the Theia backend needs to be started.
This can either be done with the `Launch Browser Backend` launch config or by running `yarn start` in the `examples/browser-app` directory.
```

2021-07-26 09:14 UTC, sdirix commented on scripts/performance/README.md
> +The script accepts the following parameters:
```suggestion
The script accepts the following optional parameters:
```

2021-07-26 09:20 UTC, sdirix commented on scripts/performance/README.md
> +-   `--url`: Point Theia to a url for example for specifying a specifc workspace (default: `http://localhost:3000/#/<absolutePathToWorkspaceFolder>`)
Default is workspace next to the script, right?
```suggestion
-   `--url`: Point Theia to a url for example for specifying a specifc workspace (default: `http://localhost:3000/#/<pathToMeasurementScript>/workspace`)
```

2021-07-26 09:21 UTC, sdirix commented on scripts/performance/measure-performance.js
> +        await page.waitForSelector('.theia-preload', { state: 'detached' });
Is `{ state: 'detached' }` even a valid option for Puppeteer? Seems to be Playwright only. What's the difference to just removing this option?

2021-07-26 09:21 UTC, sdirix commented on scripts/performance/measure-performance.js
> +        await page.waitForSelector('.fa-exclamation-triangle', { state: 'visible' });
Shouldn't this be `visible: true`?
```suggestion
        // @ts-ignore
        await page.waitForSelector('.fa-exclamation-triangle', { visible: true });
```

2021-07-26 09:58 UTC, sgraband commented on scripts/performance/measure-performance.js
> +        await page.waitForSelector('.theia-preload', { state: 'detached' });
I just removed this selector, as it does not affect the script at all. Waiting for the other selector is enough.

2021-07-26 12:42 UTC, sdirix requested changes
Two minor comments left

2021-07-26 12:42 UTC, sdirix commented on scripts/performance/README.md
> +-   `--url`: Point Theia to a url for example for specifying a specifc workspace (default: `http://localhost:3000/#/<pathToMeasurementScript>/workspace>`)
```suggestion
-   `--url`: Point Theia to a url for example for specifying a specifc workspace (default: `http://localhost:3000/#/<pathToMeasurementScript>/workspace`)
```

2021-07-26 12:42 UTC, sdirix commented on scripts/performance/README.md
> +-   `--folder`: Folder name for the generated tracing files in the `profiles` folder (default: `profiles/profile`)
The actual value of the parameter is `profile`
```suggestion
-   `--folder`: Folder name for the generated tracing files in the `profiles` folder (default: `profile`)
```

2021-07-26 13:17 UTC, sdirix requested changes
We should also add this to the changelog with a `[scripts]` prefix, e.g. "Added startup performance measurement script"

2021-07-26 13:37 UTC, sgraband commented
Rebased and added the changelog entry (PR number missing, as we do not have it yet)

2021-07-26 13:43 UTC, sdirix requested changes
Please also adapt your commit message to fit to the new PR message.

2021-07-26 13:43 UTC, sdirix commented on CHANGELOG.md
> + - [scripts] added startup performance measurement script [#](https://github.com/eclipse-theia/theia/pull/)
This is missing the Contributed by ST message

2021-07-26 14:01 UTC, sdirix approved these changes

2022-11-16 14:09 UTC, sdirix commented
Merged upstream with https://github.com/eclipse-theia/theia/pull/9777

2022-11-16 14:09 UTC, closed without merging