Add support for TaskGroup.id and isDefault.
eclipsesource/theia pull request #56
Opened 2022-11-29 07:48 UTC by tsmaeder

#### What it does

Adds support for id and isDefault and includes a small drive-by fix in the Task implementation where the taskRunOptions object was not properly initialized.

Fixes #11519

Contributed on behalf of ST Microelectronics

#### How to test
1. Install the attached vscode extension. It is built from https://github.com/tsmaeder/castletest
2. Open a workspace that generates some tasks. I use the source of Theia
3. Configure some tasks, playing with the "id" and "default" fields
4. Inspect the task by invoking "Dump task info to console" from the command palette and make sure the right values are shown for "isDefault" and "id".

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2022-11-29 07:48 UTC, tsmaeder commented
[castletest-0.0.1.zip](https://github.com/eclipsesource/theia/files/10110853/castletest-0.0.1.zip)

2022-12-01 13:12 UTC, tsmaeder commented
> Why do we have two terms for the same field (kind and id)?

I'm glad you asked ;-) Because tasks are a mess: their typing is a mix of the schema of the tasks.json file, our internal structures and what the VS Code API wants. So task kind and task id are _NOT_ really the same thing: they might be the id of a TaskGroup object from the VSCode API or they might be a string that is written in a tasks.json (where only "build" and "test" are allowed, by the way). Calling it `id` would just paper over the lack of clarity there. Different things should be name differently!

2022-12-01 13:41 UTC, sgraband commented on packages/plugin-ext/src/common/plugin-api-rpc.ts
> +export type TaskGroupKind = 'build' | 'test' | 'rebuild' | 'clean'
```suggestion
export type TaskGroupKind = 'build' | 'test' | 'rebuild' | 'clean';
```

Seems like the linter requires a semicolon here.

2022-12-01 13:43 UTC, sgraband requested changes
Thanks for the clarification. The linter and the tests are complaining, though. Could you check that?

2022-12-02 13:22 UTC, tsmaeder commented
The tests complain that that "Values have same structure but are not reference-equal". I suspect it's because the TaskGroup constants use the unwrapped `TaskGroup` constructor, whereas `type-converter.ts` uses the `@Es5Compat`-annotated version of the constructor. I'm not sure whether that is a real problem or not, you're probably a better judge of it (seeing that you did https://github.com/eclipse-theia/theia/pull/9436). I can fix the test, though 🤷

2022-12-02 13:54 UTC, sgraband approved these changes
Great thank you! Using the es5-wrapped constructor should not be an issue. LGTM :+1:

2026-06-26 13:52 UTC, ndoschek commented
Clsoed via https://github.com/eclipse-theia/theia/pull/11944

2026-06-26 13:52 UTC, closed without merging