Issues/11702
eclipsesource/theia pull request #58
Opened 2022-12-06 12:53 UTC by rschnekenbu

#### What it does

_Add Comment#timestamp optional property_
This adds the timeStamp optional property from Comment to improve vscode api coverage. It also displays the timestamp of each comments in the Comment Thread widget

Fixes #11702 

Contributed on behalf of ST Microelectronics

#### How to test 
Note: there are currently some issues with menus, since theia 1.28.0. This is due to #11290, integrated in 1.28.0. Prior to this change, the comment sample works on theia 1.27.0. So to test this change, I cherry-picked my commit on top of 1.27.0 tag. Please see also #11730 for this menu issues.
1. Install forked extension [#comment-sample-0.0.1](https://github.com/rschnekenbu/vscode-extension-samples/releases/tag/0.0.1) vsix file
2. Create a comment using the side bar while comparing 2 test files. 
![addCommentTimeStamp](https://user-images.githubusercontent.com/3964263/205917926-9c606ad0-5d9f-40ee-8c6b-7c56a266525a.gif)

4. The timestamp should be displayed along the user name.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2022-12-06 12:54 UTC, rschnekenbu commented
As a note, the 4 first commits are only commits on theia/master not yet available on eclipsesource/master. Only [2df36ae](https://github.com/eclipsesource/theia/pull/58/commits/2df36ae3bebbef3ddc4b2ccd960a713f1a3f6e51) is relevant

2022-12-13 13:55 UTC, lucas-koehler requested changes

2022-12-13 13:55 UTC, lucas-koehler commented on packages/plugin-ext/src/main/browser/comments/comment-thread-widget.tsx
> +        return timeStamp.toLocaleDateString();
When I test this rebased onto `v1.27.0`, `timestamp` was already a `string` here. Thus, this method did not exist and an exception was thrown

2022-12-15 15:41 UTC, rschnekenbu commented
New 'basic' version of timestamp support using a string rather than a date.
Best would may be to develop a DateDTO, but currently Date is only used for Comment#timeStamp in the VS Code APIs.

2022-12-15 16:29 UTC, lucas-koehler reviewed
Showing the timestamp works now, thanks!
However, I think a better way to serialize the date is using the ISO date format instead of serializing the full JSON object.
See inline suggestions for changing this and other minor fixes

2022-12-15 16:29 UTC, lucas-koehler commented on packages/plugin-ext/src/plugin/comments.ts
> +    const _date = theiaComment.timeStamp ? theiaComment.timeStamp.toJSON() : undefined;
```suggestion
    const date = theiaComment.timeStamp ? theiaComment.timeStamp.toISOString() : undefined;
```

I think a better way to serialize the date is using an ISO date. this can be done by using [Date#toISOString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).
Then I'd change the comment in [plugin-api-rpc-model.ts](https://github.com/eclipsesource/theia/pull/58/files#diff-090c314b5db1fac40ea5a8a22114a5cde9ac27a5115e497471b4891d2397d370) to something like:
`/** Date serialized as ISO string */`

Regarding naming: I think using the underscore here is against Theia's coding guidelines for variable names. AFAIK this is only used for ununsed method parameters and properties that have `get` and/or `set` methods

2022-12-15 16:29 UTC, lucas-koehler commented on packages/plugin-ext/src/plugin/comments.ts
> +        timeStamp: _date,
See above

```suggestion
        timeStamp: date,
```

2022-12-15 16:29 UTC, lucas-koehler commented on packages/plugin-ext/src/common/plugin-api-rpc-model.ts
> +    // note: timestamp is a string rather than a Date (easier to pass to frontend)
```suggestion
    /** Timestamp serialized as ISO date string via Date.prototype.toISOString */
```

2022-12-19 10:39 UTC, rschnekenbu commented
Thanks for your review, @lucas-koehler. I tested again the branch on 1.27.0, the timestamp is still displayed with your last suggestions.
I can now push it to main repo.

2022-12-19 10:57 UTC, lucas-koehler approved these changes

2023-01-11 14:48 UTC, rschnekenbu commented
close PR as the one on main fork has been merged (https://github.com/eclipse-theia/theia/pull/12007/)

2023-01-11 14:48 UTC, closed without merging