11503 terminal profile api 2
eclipsesource/theia pull request #60
Opened 2022-12-27 08:31 UTC by tsmaeder

#### What it does
Adds support for terminal profiles. 

Fixes [#11503](https://github.com/eclipse-theia/theia/issues/11503)

* UI and service to manage terminal profiles
* Handle profiles in preferences according to VS Code schema
* API and contribution markup for contributing profiles and activation event handling

contributed on behalf of ST Microelectronics

#### How to test
This PR adds two new items under the "Terminal" menu: "New Terminal...", which allows to select a profile and use it to open a terminal and "Choose Default Profile", which selects the profile to be used when selecting "New Terminal" from the menu.
Some profiles are added by default ("cmd" by default on windows), but they can also be contributed by plugins or defined in the preferences. 
Here are two extensions that can be used to test contributed terminals:

[plugins.zip](https://github.com/eclipsesource/theia/files/10306957/plugins.zip)

One contributes a shell terminal profile ("JavaScript Debug Terminal") and the other a pseudo-pty terminal ("My Extension Terminal"). 

Adding profiles via terminals is described here:

https://code.visualstudio.com/docs/terminal/profiles

Note that terminal "source"s have not been implemented. Theia will accept the syntax, but the resulting profiles will not work.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2023-01-05 09:15 UTC, tortmayr requested changes
Terminal profiles are definitely a nice addition to Theia, thanks!

In general the change looks good to me and seems to work well for the most part. (Tested on Linux & Windows)

However, there seems to be a problem with persisting the setting for the default profile. 
If I change the default terminal profile, everything works as expected during the active session (i.e. new terminals spawn with the new profile), When I close and reopen Theia the setting is lost and the system default for the terminal profile is used again. The corresponding setting (`terminal.integrated.defaultProfileXX`) is set but  it seems to be ignored.

Secondly, I noticed that the `cmd` Profile is not working on Window when using node 14. For me it just spawns empty new terminal windows which I cannot interact with.
With node 16 everything works as expected.

The default Profile for Linux is also called`CMD` which is a bit confusing.

Compared to VS Code I noticed that some nice-to-have features are missing. They don't necessarily have to be part of this initial contribution and can also be tackled with a follow-up PR:
- No system default profiles.
 Depending on the underlying OS VS Code creates default profiles for the installed terminals e.g. "CMD, PowerShell & Gitbash" for Windows or "Bash, Zash and Tmux" for Linux. This would be really usefull for Theia as well
 
- In VS Code the settings UI element for setting the default profile is a selection box rather than a plain text box. Maybe we should implement it in the same way in Theia?

2023-01-09 07:44 UTC, tsmaeder commented
> However, there seems to be a problem with persisting the setting for the default profile. If I change the default terminal profile, everything works as expected during the active session (i.e. new terminals spawn with the new profile), When I close and reopen Theia the setting is lost and the system default for the terminal profile is used again. The corresponding setting (`terminal.integrated.defaultProfileXX`) is set but it seems to be ignored.

that's odd. I'll have a look.
> 
> Secondly, I noticed that the `cmd` Profile is not working on Window when using node 14. For me it just spawns empty new terminal windows which I cannot interact with. With node 16 everything works as expected.

Good catch, strange that this would make a difference 🤷‍♂️ 

> 
> The default Profile for Linux is also called`CMD` which is a bit confusing.

I guess that's a copy/paste error in the preferences
> 
> Compared to VS Code I noticed that some nice-to-have features are missing. They don't necessarily have to be part of this initial contribution and can also be tackled with a follow-up PR:
> 
>     * No system default profiles.
>       Depending on the underlying OS VS Code creates default profiles for the installed terminals e.g. "CMD, PowerShell & Gitbash" for Windows or "Bash, Zash and Tmux" for Linux. This would be really usefull for Theia as well

Yes, I considered that out of scope, given that the issue I'm fixing is to implement the VS Code profiles API.
> 
>     * In VS Code the settings UI element for setting the default profile is a selection box rather than a plain text box. Maybe we should implement it in the same way in Theia?

Which UI element do you mean? The one when you do F1-Profile: Select Default Profile? How is that different from what we have?

2023-01-12 13:13 UTC, tsmaeder commented on packages/plugin-ext/src/common/plugin-protocol.ts
> +    profiles: {
No real reason, and you're right: it would be more consistent with the style of the other declarations in the file.

2023-01-12 14:04 UTC, tsmaeder commented on packages/plugin-ext/src/main/browser/plugin-contribution-handler.ts
> +        const self = this;
Yes, `this` refers to the `TerminalProfile` instance, not the `PluginContributionHandler`, so it would not compile.

2023-01-12 14:45 UTC, tsmaeder commented
@tortmayr I just built and ran the browser version with nodejs v14.21.2. Running the 'cmd' profile works just fine for me. Do you maybe have a 'cmd' profile defined in the settings which might override the built-in?

2023-01-12 15:12 UTC, tsmaeder commented
Seems electron has a problem running cmd on window. Investigating.

2023-01-12 16:18 UTC, tsmaeder commented
> > Which UI element do you mean? The one when you do F1-Profile: Select Default Profile? How is that different from what we have?
> 
> I was talking about the text box in the Preferences UI for setting the default profile (`terminal.integrated.defaultProfile.xxx`):

Ah, OK. T.b.h, I would defer that to a future task: I don't think it's that important, since there is an alternative via the terminal menu (which I would expect most people to use), and I'd would rather focus on making sure we get the PR merged for the community release, as this would allow us to raise the support API version.

2023-01-12 16:59 UTC, tortmayr approved these changes
Thanks Thomas. Change looks good to me now. 👍🏼 

I also can no longer reproduce the node 14 issues.

2026-06-26 13:54 UTC, ndoschek commented
Closed via upstream PR https://github.com/eclipse-theia/theia/pull/12066

2026-06-26 13:54 UTC, closed without merging