[Internal review] playwright: Update to latest versions and add new page objects
eclipsesource/theia pull request #75
Opened 2023-04-03 09:08 UTC by ndoschek

#### What it does

- Update `playwright` to the latest version
  - Update test configuration to adapt to latest version
  - Remove obsolete multiple config files and scripts
- Add page objects for OutputView, OutputChannel, Toolbar
- Extend tests by testing the new page objects
- Extend ExplorerView tests with compact folders
- Extend QuickCommand tests
- Update README

Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>

#### How to test

- Run playwright tests via `yarn test:playwright` from root directory

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2023-04-05 07:53 UTC, planger requested changes
Excellent job, thank you!
I also tested the VS Code Playwright extension a bit more and it really seems to be very helpful. Thanks for updating Playwright and pointing us to this nice extension!
Also the new page objects are pretty neat.

I just had a few comments, especially about updating and clarifying the documentation. Otherwise, this looks great. Thanks!

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/DEVELOPING.md
> +To watch, run `yarn watch` in the root of this package. This ensures, that the testing code is up-to-date also for executing via the Playwright VSCode Extension.
```suggestion
Run `yarn watch` in the root of this package to rebuild the test code after each change. This ensures, that the executed tests are up to date also when running them with the [Playwright VS Code Extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright).
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/DEVELOPING.md
- I also had to run `npx playwright install`. Should we mention this here and in the `GETTING_STARTED.md`?
- The section *Prerequisites* seems to be outdated now as we don't have to run `yarn browser start`. I suggest to mention that you can execute Theia with `yarn browser start` or via the launch config manually to run the Playwright tests against this specific Theia backend (which may be useful if you also want to debug the Theia backend during the test run), or you omit starting Theia and Playwright will do this for you.
- I feel we should also mention the VS Code Playwright Test extension in this guide again similar to how we mention it in the `GETTING_STARTED.md`
- Please spell VS Code consistently *VS Code* and not *VSCode*

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/GETTING_STARTED.md
> +This is valid for executing tests via the VSCode extension and via CLI.
```suggestion
This is valid for executing tests with the VS Code Playwright extension or from your command line.
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/GETTING_STARTED.md
> +For quick and easy execution of tests in VSCode, please install the extension [`ms-playwright.playwright`](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright).
```suggestion
For quick and easy execution of tests in VS Code, we recommend to use the [VS Code Playwright extension (`ms-playwright.playwright`)](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright).
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/GETTING_STARTED.md
> +To quickly start the playwright tests, open the playwright testing extension and click the `Run Tests` button on the top toolbar or the `Run Test` for a particular test.
```suggestion
Once you have installed the VS Code Playwright test extension, open the *Test* view and click the `Run Tests` button on the top toolbar or the `Run Test` button for a particular test.
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/GETTING_STARTED.md
> +To run the tests headful, simply enable the checkbox `Show browser` in the Playwright testing extension.
```suggestion
To run the tests headful, simply enable the checkbox `Show browser` in the Playwright section of the *Test* view.
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/GETTING_STARTED.md
> +### Debugging the tests via the Playwright extension
```suggestion
### Debugging the tests via the VS Code Playwright extension
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/GETTING_STARTED.md
> +To debug playwright tests, open the playwright testing extension and click the `Debug Tests` button on the top toolbar or the `Debug Test` for a particular test.
```suggestion
To debug Playwright tests, open the *Test* view in VS Code and click the `Debug Tests` button on the top toolbar or the `Debug Test` for a particular test.
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/GETTING_STARTED.md
> +For an advanced test development experience, Playwright introduced the UI Mode. To enable this, simply add the flag `--ui` to the CLI command.
```suggestion
For an advanced test development experience, Playwright provides the so-called *UI Mode*. To enable this, simply add the flag `--ui` to the CLI command.
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/docs/GETTING_STARTED.md
> +I.e. run the following command:
```suggestion
```

2023-04-05 07:53 UTC, planger commented on examples/playwright/src/theia-explorer-view.ts
> +        const folderElement = await viewElement?.$(selector);
Is this safe, if the files have not been yet loaded into the file explorer? We recently had a few flaky tests because we expected file nodes whereas the file explorer has not yet been populated. Therefore, we've switched to waits in a few places, see
* https://github.com/eclipse-theia/theia/pull/12373
* https://github.com/eclipse-theia/theia/pull/12310

2023-04-05 07:53 UTC, planger commented on examples/playwright/src/theia-output-channel.ts
This class duplicates quite a lot of code from `TheiaTextEditor`. Couldn't we extract a helper class (e.g. `new MonacoEditor(selector)`), move this shared code into that class and use this class from both the output channel and the `TheiaTextEditor` page objects?

2023-04-05 07:53 UTC, planger commented on examples/playwright/src/theia-output-view.ts
> +        const contentPanel = await this.page.$('#theia-bottom-content-panel');
Shouldn't we active the view first?

2023-04-05 07:53 UTC, planger commented on examples/playwright/src/theia-output-view.ts
> +        const channel = new TheiaOutputViewChannel(
Shouldn't we active the view first?

2023-04-05 07:53 UTC, planger commented on examples/playwright/src/theia-output-view.ts
> +        const contentPanel = await this.page.$('#theia-bottom-content-panel');
Shouldn't we active the view first?
Also, shouldn't we use waitFor... instead of `page.$` as we expect the channel to be available?

2023-04-05 07:57 UTC, planger commented
Ah and also please make sure the fixes of https://github.com/eclipse-theia/theia/pull/12373 and https://github.com/eclipse-theia/theia/pull/12310 are incorporated (also in new code) to avoid having flaky file explorer tests again.

2023-04-06 10:12 UTC, ndoschek commented on examples/playwright/docs/DEVELOPING.md
> I also had to run npx playwright install. Should we mention this here and in the GETTING_STARTED.md?

Thanks for catching that! I had another look at the scripts and basically the build step had to be triggered manually and linting was actually never executed.
I adapted the scripts and changed to make use of the `theiaext` scripts.
I tested with a clean repo and now running `yarn` should install all necessary playwright deps and browser

2023-04-06 10:14 UTC, ndoschek commented
Thank you very much for your review @planger!
I addressed your comments in a following commit and added some comments inline to yours as well.

2023-04-06 11:06 UTC, planger requested changes
Excellent, thank you!

If I didn't misunderstand anything, we don't install the dependencies of this package when running `yarn` in the root, right? Because I think there has been a change (https://github.com/eclipse-theia/theia/pull/12248) to avoid that on purpose and with that avoid slowing down the Theia build. Thus, we should make sure building the root Theia repo doesn't automatically download the Playwright dependencies.

Just a few more minors below. If those are addressed / confirmed, feel free to open the PR against Theia directly.

Thank you!

2023-04-06 11:06 UTC, planger commented on examples/playwright/package.json
>      "ui-tests-report": "yarn ui-tests-report-generate && allure open allure-results/allure-report"
I'm not so sure it is a good idea to use `theiaext` as this is not really a Theia extension. I don't know exactly what the implications are but it may open doors to issues in the future, doesn't it?

2023-04-06 11:06 UTC, planger commented on examples/playwright/src/theia-explorer-view.ts
> +        const folderElement = await viewElement?.$(selector);
Did you double-check the changes of the two PRs above to avoid re-introducing flakiness with the compact file support?

2023-04-06 11:58 UTC, ndoschek commented on examples/playwright/package.json
>      "ui-tests-report": "yarn ui-tests-report-generate && allure open allure-results/allure-report"
Yes that sounds very reasonable, I used it in the first place as I had issues with running ESLint, but I could find a way around that. I reverted those changes again and do not call the ext scripts now anymore.

2023-04-06 11:58 UTC, ndoschek commented on examples/playwright/src/theia-explorer-view.ts
> +        const folderElement = await viewElement?.$(selector);
Oh sorry I overlooked that previously. I added a `waitForVisibleFileNodes` to the compact file state getter.

2023-04-06 12:14 UTC, ndoschek commented on examples/playwright/docs/DEVELOPING.md
See https://github.com/eclipsesource/theia/pull/75#discussion_r1159701504

2023-04-06 12:56 UTC, ndoschek commented
Closing in favour of https://github.com/eclipse-theia/theia/pull/12384

2023-04-06 12:56 UTC, closed without merging