Improve documentation for `TaskAPI`
eclipsesource/theia pull request #8
Opened 2020-10-01 07:04 UTC by tortmayr

Signed-off-by: Tobias Ortmayr <tortmayr@eclipsesource.com>
Contributed on behalf of STMicroelectronics

2020-10-02 16:07 UTC, koegel requested changes
Minor changes required

2020-10-02 16:07 UTC, koegel commented on packages/task/src/node/task-runner.ts
> + * A {@link TaskRunner} knows how to run and kill a task of a particular type.
It does not know how to kill a task imho.

2020-10-02 16:07 UTC, koegel commented on packages/task/src/node/task-runner.ts
> + * The {@link TaskRunnerRegistry} is the common componet for registration and provision of
```suggestion
 * The {@link TaskRunnerRegistry} is the common componet for the registration and provisioning of
```

2020-10-02 16:07 UTC, koegel commented on packages/task/src/node/task-runner.ts
> +     * Registers the given {@link TaskRunner} to execute Taks of the specified type.
```suggestion
     * Registers the given {@link TaskRunner} to execute Task of the specified type.
```

2020-10-02 16:07 UTC, koegel commented on packages/task/src/node/task.ts
> +    /** The context that can be used for aggregation */
```suggestion
    /** The optional context that can be used for aggregation */
```

2020-10-05 07:53 UTC, tortmayr commented
Thanks for the fast review. I addressed the issues and squashed the changes into a single commit

2020-10-05 08:40 UTC, koegel requested changes
Open comment from last review

2020-10-05 08:40 UTC, koegel commented on packages/task/src/node/task-runner.ts
> + * A {@link TaskRunner} knows how to run and kill a task of a particular type.
Comment still open

2020-10-05 08:49 UTC, tortmayr commented on packages/task/src/node/task-runner.ts
> + * A {@link TaskRunner} knows how to run and kill a task of a particular type.
Fixed

2020-10-05 09:55 UTC, koegel approved these changes

2022-11-16 14:03 UTC, sdirix commented
Merged upstream with https://github.com/eclipse-theia/theia/pull/8695

2022-11-16 14:03 UTC, closed without merging