[WIP] Enable recording of stopwatch results
eclipsesource/theia pull request #85
Opened 2023-07-26 15:49 UTC by tortmayr

Introduce `MeasurementResults` that capture a stopwatch execution in a serializable format. Add `onMeasurementResult` event emitter to stopwatch class. Add a metrics contribution to `@theia/metrics` that collects all measurement results of frontend and backend processes

#### What it does

#### How to test

#### Review checklist

- [ ] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2023-07-27 10:09 UTC, planger approved these changes
Thanks, looks good to me! :+1:

2023-07-27 10:47 UTC, sdirix reviewed
In general it works for me!

When starting the browser example, sadly most of the backend startup measurements are lost and are not retrievable via the `/metrics` endpoint, probably because we are not yet listening to them. Would be great if we could find a way to output them too.

2023-07-27 10:47 UTC, sdirix commented on packages/core/src/common/performance/measurement.ts
> +    startTime: number
```suggestion
    /** The time when the measurement recording has been started */
    startTime: number;
```

2023-07-27 10:47 UTC, sdirix commented on packages/metrics/src/node/measurement-metrics-contribution.ts
> +        const labels: string = `id="${id}", name="${name}" ,startTime="${startTime}", elapsed="${elapsed}", owner="${owner}", context="${context}"`;
```suggestion
        const labels: string = `id="${id}", name="${name}", startTime="${startTime}", elapsed="${elapsed}", owner="${owner}", context="${context}"`;
```

2023-07-27 10:47 UTC, sdirix commented on packages/metrics/src/node/measurement-metrics-contribution.ts
> +        const labels: string = `id="${id}", name="${name}" ,startTime="${startTime}", elapsed="${elapsed}", owner="${owner}", context="${context}"`;
The `elapsed` is not really needed here, right? We output it as the value of the metric anyway

2023-07-28 13:04 UTC, tortmayr commented
@sdirix Thanks for the review.I have reworked the PR to ensure that we properly record all measurement results.
Could you please have a second look?
Also the metrics contribution is now only reporting if the application has been started in debug mode (i.e. log-level===debug)

2023-07-28 14:26 UTC, sdirix requested changes
Works for me! Found only one small issue. 

Shall we really log the context? It seems to be always `undefined` for me. What do you think?

2023-07-28 14:26 UTC, sdirix commented on packages/metrics/src/node/measurement-metrics-contribution.ts
> +    protected metrics: string;
this.metrics is initially `undefined`. If no measurements are added then this contribution adds `undefined` to the metrics. If some are added then `undefined` will be prefixed.

2023-08-08 10:44 UTC, closed without merging