Add documentation for `FileService` & `FileSystemProvider`
eclipsesource/theia pull request #9
Opened 2020-10-01 13:57 UTC by tortmayr

Signed-off-by: Tobias Ortmayr <tortmayr@eclipsesource.com>
Contributed on behalf of STMicroelectronics

2020-10-02 15:48 UTC, koegel requested changes
Some minor suggestions and a question

2020-10-02 15:48 UTC, koegel commented on packages/filesystem/src/browser/file-service.ts
> +    /**
Is all this whitespace change really intended?

2020-10-02 15:48 UTC, koegel commented on packages/filesystem/src/browser/file-service.ts
> +    /** The affected file system provider for which this event was fired. */
Why is it optional?

2020-10-02 15:48 UTC, koegel commented on packages/filesystem/src/browser/file-service.ts
> + * This service manages all registered {@link FileSystemProvider}. In a nutshell, the {@link FileService} acts as a facade for all registered
```suggestion
 * It manages all registered {@link FileSystemProvider}s and
```

2020-10-02 15:48 UTC, koegel commented on packages/filesystem/src/browser/file-service.ts
> + * The {@link FileService} is the common frontend component responsible for all interactions with file systems.
```suggestion
 * The {@link FileService} is the common facade responsible for all interactions with file systems.
```

2020-10-02 15:48 UTC, koegel commented on packages/filesystem/src/browser/file-service.ts
> + * {@link FileSystemProvider}s and will forward calls to the responsible {@link FileSystemProvider} (this is determined by the scheme).
```suggestion
 *  forwards calls to the responsible {@link FileSystemProvider}, determined by the scheme.
```

2020-10-05 08:01 UTC, tortmayr commented on packages/filesystem/src/browser/file-service.ts
> +    /** The affected file system provider for which this event was fired. */
I don't know. I cannot derive this from the given code. Every time this event is fired the `provider` property is defined. So in my opinion this should not be optional.

2020-10-05 08:15 UTC, tortmayr commented on packages/filesystem/src/browser/file-service.ts
> +    /**
Fixed

2020-10-05 08:34 UTC, koegel approved these changes

2020-10-05 08:34 UTC, koegel commented on packages/filesystem/src/browser/file-service.ts
> +    /** The affected file system provider for which this event was fired. */
OK, maybe this is something we should bring up to the Theia devs on a different channel, we will discuss

2020-10-05 10:50 UTC, tortmayr commented on packages/filesystem/src/common/files.ts
> +     * @retunrs A `Disposable` that can be invoked to stop watching the resource.
```suggestion
     * @returns A `Disposable` that can be invoked to stop watching the resource.
```

2020-10-05 10:55 UTC, koegel approved these changes

2022-11-16 14:02 UTC, sdirix commented
Merged upstream with https://github.com/eclipse-theia/theia/pull/8596

2022-11-16 14:02 UTC, closed without merging