[vscode] support of editor.indentSize
eclipsesource/theia pull request #94
Opened 2023-11-14 09:39 UTC by rschnekenbu

#### What it does

Fix missing API TextEditorOptions.indentSize made public on vscode 1.83 (was a proposed API before). 
The behavior is available, but the preference requires an uplift of the monaco version. It is not yet available in the generated preferences. 

Note; changelog will be pushed once PR is created against main repo.

Fixes #13058

Contributed on behalf of ST Microelectronics

#### How to test 
The test can be done on a text file, using "Indent using spaces" and "Indent using tabs" commands. The behavior should be the same as before. Only the internals have changed. 
The preferences test has to wait the monaco uplift.

The following provided extension can also show the value of identSize when the value has changed with an information message:
- zip: [indent-sample-0.0.1.zip](https://github.com/eclipse-theia/theia/files/13347091/indent-sample-0.0.1.zip)
- src: [indent-sample-src-0.01.zip](https://github.com/eclipse-theia/theia/files/13347093/indent-sample-src-0.01.zip)

#### Follow-ups

Preferences need to be supported once a monaco uplift has been performed.

#### Review checklist

- [x] As an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- [ ] As a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

2023-11-22 14:10 UTC, tsmaeder requested changes

2023-11-22 14:10 UTC, tsmaeder commented on packages/plugin-ext/src/plugin/text-editor.ts
> +        const indentSize = this.validateIndentSize(val);
The doc says: 

> When getting a text editor's options, this property will always be a number (resolved). When setting a text editor's options, this property is optional and it can be a number or "tabSize".

with the code as it is, I believe when I do 
```
options.indentSize= 'tabSize?;
console.log(options.indentSize);
```
I would see "tabSize" in the console, not the numeric value of the tab size.

2023-11-23 15:03 UTC, rschnekenbu commented on packages/plugin-ext/src/plugin/text-editor.ts
> +            if (val === 'tabSize') {
indeed, fixed with new version

2023-11-23 15:17 UTC, rschnekenbu commented on packages/monaco/src/browser/monaco-command.ts
> +                        indentSize: size || tabSize,
To be honest, I only did the same behavior as vscode is doing (https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/indentation/browser/indentation.ts#L254). My initial implementation was to run 2 different cases, if we use spaces or not. If not, I was only updating tabSize. If useSpace, then I would have only updated the indentSize. But the code would have been more complex, and results should be the same.
In this case, size should only be a number as we can pick from 1 to 8.

2023-11-27 08:22 UTC, rschnekenbu commented
@tsmaeder, the PR is ready for review again. I did some changes also in tabSize management to align the APIs and the documentation.

2023-11-27 13:42 UTC, tsmaeder commented on packages/plugin-ext/src/plugin/text-editor.ts
> +        const indentSize = this.validateIndentSize(val);
I'm not seeing any changes to this code in your latest commit. Something missing in it?

2023-11-27 13:59 UTC, tsmaeder approved these changes

2023-11-27 14:07 UTC, rschnekenbu commented
closed in favor of PR on main repo

2023-11-27 14:07 UTC, closed without merging